import { ClerkLoaded, ClerkLoading, ClerkProvider } from '@clerk/nextjs';
//THIS IS A TEST COMMENT
import type { Metadata } from 'next';

import localFont from 'next/font/local';

import LoadingState from '@/components/LoadingState';
import Navbar from '@/components/Navbar';
import './globals.css';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased `}
				>
					<Navbar />
					<div className="max-w-6xl mx-auto">
						<ClerkLoading>
							<LoadingState />
						</ClerkLoading>
						<ClerkLoaded>
							<div className="flex flex-col h-screen">{children}</div>
						</ClerkLoaded>
					</div>
				</body>
			</html>
		</ClerkProvider>
	);
}
